CREATE TYPE "public"."error_type" AS ENUM('grammar', 'vocabulary', 'naturalness', 'pronunciation', 'listening', 'tone', 'appropriateness');--> statement-breakpoint
CREATE TYPE "public"."lesson_pack_status" AS ENUM('accepted', 'rejected', 'needs_repair');--> statement-breakpoint
CREATE TYPE "public"."source_mode" AS ENUM('manual_free_relay', 'local_model', 'paid_api');--> statement-breakpoint
CREATE TYPE "public"."source_type" AS ENUM('listening', 'roleplay', 'writing', 'feedback');--> statement-breakpoint
CREATE TYPE "public"."task_type" AS ENUM('lesson_generation', 'json_repair', 'feedback_scoring', 'retry_generation');--> statement-breakpoint
CREATE TABLE "chunks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chunks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lesson_pack_id" bigint NOT NULL,
	"phrase" text NOT NULL,
	"meaning" text NOT NULL,
	"example" text NOT NULL,
	"source_context" text,
	"times_recognized" integer DEFAULT 0 NOT NULL,
	"times_reused_correctly" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "error_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "error_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lesson_pack_id" bigint NOT NULL,
	"source_type" "source_type" NOT NULL,
	"error_type" "error_type" NOT NULL,
	"evidence" text NOT NULL,
	"correction" text NOT NULL,
	"why_it_matters" text NOT NULL,
	"retry_priority" text NOT NULL,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lesson_packs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lesson_packs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"topic_id" bigint,
	"schema_version" text,
	"prompt" text NOT NULL,
	"raw_ai_output" text NOT NULL,
	"validated_json" jsonb,
	"source_mode" "source_mode" NOT NULL,
	"provider_or_site" text,
	"model_name" text,
	"status" "lesson_pack_status" NOT NULL,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"accepted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "listening_attempts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "listening_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lesson_pack_id" bigint NOT NULL,
	"listening_input_id" bigint NOT NULL,
	"gist_answers" jsonb NOT NULL,
	"detail_answers" jsonb NOT NULL,
	"key_phrase_answers" jsonb NOT NULL,
	"replay_count" integer DEFAULT 0 NOT NULL,
	"score_gist" real DEFAULT 0 NOT NULL,
	"score_detail" real DEFAULT 0 NOT NULL,
	"score_key_phrase" real DEFAULT 0 NOT NULL,
	"missed_details" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "listening_inputs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "listening_inputs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lesson_pack_id" bigint NOT NULL,
	"script" text NOT NULL,
	"audio_path" text,
	"recommended_voice" text NOT NULL,
	"accent" text NOT NULL,
	"speed" text NOT NULL,
	"duration_seconds" integer NOT NULL,
	"transcript_visible_after_attempt" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "model_outputs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "model_outputs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"task_type" "task_type" NOT NULL,
	"source_mode" "source_mode" NOT NULL,
	"provider_or_site" text,
	"model_name" text,
	"prompt" text NOT NULL,
	"raw_response" text NOT NULL,
	"parsed_json" jsonb,
	"accepted" boolean NOT NULL,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "retry_drills" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "retry_drills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lesson_pack_id" bigint NOT NULL,
	"error_log_id" bigint,
	"instruction" text NOT NULL,
	"items_json" jsonb NOT NULL,
	"learner_result" text,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "roleplay_turns" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roleplay_turns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lesson_pack_id" bigint NOT NULL,
	"turn_index" integer NOT NULL,
	"ai_prompt" text NOT NULL,
	"learner_goal" text NOT NULL,
	"learner_response" text,
	"feedback_json" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "topics" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "topics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"topic" text NOT NULL,
	"target_language" text NOT NULL,
	"learner_native_language" text NOT NULL,
	"cefr_level" text NOT NULL,
	"situation" text NOT NULL,
	"session_minutes" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "writing_submissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "writing_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lesson_pack_id" bigint NOT NULL,
	"task" text NOT NULL,
	"constraints_json" jsonb NOT NULL,
	"target_chunks_json" jsonb NOT NULL,
	"draft" text,
	"corrected_version" text,
	"rubric_scores_json" jsonb,
	"feedback_json" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "chunks" ADD CONSTRAINT "chunks_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "error_log" ADD CONSTRAINT "error_log_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_packs" ADD CONSTRAINT "lesson_packs_topic_id_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "listening_attempts" ADD CONSTRAINT "listening_attempts_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "listening_attempts" ADD CONSTRAINT "listening_attempts_listening_input_id_listening_inputs_id_fk" FOREIGN KEY ("listening_input_id") REFERENCES "public"."listening_inputs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "listening_inputs" ADD CONSTRAINT "listening_inputs_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retry_drills" ADD CONSTRAINT "retry_drills_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retry_drills" ADD CONSTRAINT "retry_drills_error_log_id_error_log_id_fk" FOREIGN KEY ("error_log_id") REFERENCES "public"."error_log"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "roleplay_turns" ADD CONSTRAINT "roleplay_turns_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writing_submissions" ADD CONSTRAINT "writing_submissions_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chunks_lesson_pack_id_idx" ON "chunks" USING btree ("lesson_pack_id");--> statement-breakpoint
CREATE INDEX "error_log_lesson_pack_id_idx" ON "error_log" USING btree ("lesson_pack_id");--> statement-breakpoint
CREATE INDEX "error_log_error_type_idx" ON "error_log" USING btree ("error_type");--> statement-breakpoint
CREATE INDEX "lesson_packs_topic_id_idx" ON "lesson_packs" USING btree ("topic_id");--> statement-breakpoint
CREATE INDEX "lesson_packs_status_created_at_idx" ON "lesson_packs" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "listening_attempts_lesson_pack_id_idx" ON "listening_attempts" USING btree ("lesson_pack_id");--> statement-breakpoint
CREATE INDEX "listening_attempts_created_at_idx" ON "listening_attempts" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "listening_inputs_lesson_pack_id_idx" ON "listening_inputs" USING btree ("lesson_pack_id");--> statement-breakpoint
CREATE INDEX "model_outputs_task_type_idx" ON "model_outputs" USING btree ("task_type");--> statement-breakpoint
CREATE INDEX "model_outputs_source_mode_idx" ON "model_outputs" USING btree ("source_mode");--> statement-breakpoint
CREATE INDEX "model_outputs_created_at_idx" ON "model_outputs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "retry_drills_lesson_pack_id_idx" ON "retry_drills" USING btree ("lesson_pack_id");--> statement-breakpoint
CREATE INDEX "retry_drills_error_log_id_idx" ON "retry_drills" USING btree ("error_log_id");--> statement-breakpoint
CREATE INDEX "retry_drills_completed_at_idx" ON "retry_drills" USING btree ("completed_at");--> statement-breakpoint
CREATE INDEX "roleplay_turns_lesson_pack_id_idx" ON "roleplay_turns" USING btree ("lesson_pack_id");--> statement-breakpoint
CREATE INDEX "writing_submissions_lesson_pack_id_idx" ON "writing_submissions" USING btree ("lesson_pack_id");