CREATE TABLE "speaking_attempts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "speaking_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer DEFAULT 1 NOT NULL,
	"lesson_pack_id" bigint NOT NULL,
	"prompt_type" text NOT NULL,
	"prompt_ref" text,
	"audio_path" text,
	"transcript" text,
	"stt_provider" text,
	"stt_status" text DEFAULT 'not_requested' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "speaking_attempts" ADD CONSTRAINT "speaking_attempts_lesson_pack_id_lesson_packs_id_fk" FOREIGN KEY ("lesson_pack_id") REFERENCES "public"."lesson_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "speaking_attempts_lesson_pack_id_idx" ON "speaking_attempts" USING btree ("lesson_pack_id");--> statement-breakpoint
CREATE INDEX "speaking_attempts_created_at_idx" ON "speaking_attempts" USING btree ("created_at");